import type {
	AISettings,
	BillingUsage,
	Concept,
	DailyMission,
	Flashcard,
	LearningPlan,
	ProgressSnapshot,
	RecallAttempt,
	Resource,
	StudySession,
	TutorMessage,
	User,
	Workspace,
} from "@/lib/types";

export const mockUser: User = {
	id: "user-shaswat",
	name: "Shaswat",
	email: "sh20raj@gmail.com",
	avatarInitials: "SR",
	timezone: "Asia/Kolkata",
	plan: "pro",
	streakDays: 6,
	dailyTargetMinutes: 90,
	preferredSessionMinutes: 25,
	learningGoal: "exam-prep",
	knowledgeLevel: "intermediate",
	onboardingCompleted: true,
};

export const mockWorkspaces: Workspace[] = [
	{
		id: "ws-coa",
		slug: "computer-organization-architecture",
		title: "Computer Organization & Architecture",
		description: "End-sem prep for memory hierarchy, cache mapping, pipelining, and virtual memory.",
		icon: "Cpu",
		color: "indigo",
		status: "active",
		goal: "COA End Sem",
		deadline: "2026-05-24T18:00:00.000+05:30",
		progress: 64,
		memoryScore: 78,
		examReadiness: 61,
		resourcesCount: 4,
		flashcardsDue: 18,
		weakConcepts: ["concept-pipeline-hazards", "concept-cache-mapping", "concept-addressing-modes", "concept-virtual-memory"],
		concepts: [
			"concept-number-systems",
			"concept-instruction-cycle",
			"concept-addressing-modes",
			"concept-memory-hierarchy",
			"concept-cache-mapping",
			"concept-direct-mapping",
			"concept-associative-mapping",
			"concept-set-associative-mapping",
			"concept-pipelining",
			"concept-pipeline-hazards",
			"concept-virtual-memory",
		],
		lastStudiedAt: "2026-05-22T07:42:00.000+05:30",
		weeklyTargetMinutes: 420,
		createdAt: "2026-05-10T09:15:00.000+05:30",
	},
	{
		id: "ws-fullstack",
		slug: "full-stack-development",
		title: "Full Stack Development",
		description: "React, Next.js, API design, database patterns, and production deployment habits.",
		icon: "Layers3",
		color: "cyan",
		status: "active",
		goal: "Ship a portfolio SaaS MVP",
		deadline: "2026-06-12T20:00:00.000+05:30",
		progress: 42,
		memoryScore: 71,
		examReadiness: 58,
		resourcesCount: 5,
		flashcardsDue: 9,
		weakConcepts: ["concept-server-actions", "concept-db-indexes"],
		concepts: ["concept-react-state", "concept-next-routing", "concept-server-actions", "concept-db-indexes"],
		lastStudiedAt: "2026-05-21T22:10:00.000+05:30",
		weeklyTargetMinutes: 300,
		createdAt: "2026-04-28T14:00:00.000+05:30",
	},
	{
		id: "ws-ml",
		slug: "machine-learning-basics",
		title: "Machine Learning Basics",
		description: "Core ML intuition across regression, classification, loss functions, and evaluation.",
		icon: "BrainCircuit",
		color: "violet",
		status: "active",
		goal: "Build reliable ML fundamentals",
		deadline: null,
		progress: 28,
		memoryScore: 63,
		examReadiness: 38,
		resourcesCount: 3,
		flashcardsDue: 7,
		weakConcepts: ["concept-regularization", "concept-gradient-descent"],
		concepts: ["concept-gradient-descent", "concept-overfitting", "concept-regularization"],
		lastStudiedAt: "2026-05-19T19:30:00.000+05:30",
		weeklyTargetMinutes: 210,
		createdAt: "2026-05-02T11:05:00.000+05:30",
	},
	{
		id: "ws-vocab",
		slug: "english-vocabulary",
		title: "English Vocabulary",
		description: "High-retention vocabulary practice with roots, example sentences, and recall drills.",
		icon: "BookOpenText",
		color: "emerald",
		status: "paused",
		goal: "Improve interview and writing vocabulary",
		deadline: null,
		progress: 53,
		memoryScore: 81,
		examReadiness: 69,
		resourcesCount: 2,
		flashcardsDue: 8,
		weakConcepts: ["concept-word-roots"],
		concepts: ["concept-word-roots", "concept-context-clues"],
		lastStudiedAt: "2026-05-17T08:15:00.000+05:30",
		weeklyTargetMinutes: 120,
		createdAt: "2026-03-20T16:45:00.000+05:30",
	},
];

export const mockResources: Resource[] = [
	{
		id: "res-coa-module-1",
		workspaceId: "ws-coa",
		title: "COA Module 1.pdf",
		type: "pdf",
		status: "ready",
		fileName: "COA Module 1.pdf",
		sourceLabel: "PDF - Module 1",
		summary:
			"Foundational notes covering number systems, instruction cycle, addressing modes, memory hierarchy, and the first layer of cache mapping.",
		conceptsFound: 11,
		flashcardsGenerated: 38,
		weakConcepts: 4,
		lastOpenedAt: "2026-05-22T07:42:00.000+05:30",
		addedAt: "2026-05-16T10:24:00.000+05:30",
		readingTimeMinutes: 48,
		progress: 76,
		pages: 42,
		tags: ["end-sem", "module-1", "memory"],
		sections: [
			{
				id: "sec-coa-memory",
				title: "Memory hierarchy",
				summary: "Registers, cache, main memory, secondary storage, and why access latency drives hierarchy design.",
				sourceRef: "Page 4",
				conceptIds: ["concept-memory-hierarchy", "concept-cache-mapping"],
			},
			{
				id: "sec-coa-addressing",
				title: "Addressing modes",
				summary: "Immediate, direct, indirect, register, indexed, and base-relative addressing with exam examples.",
				sourceRef: "Page 9",
				conceptIds: ["concept-addressing-modes"],
			},
			{
				id: "sec-coa-pipeline",
				title: "Pipelining basics",
				summary: "Instruction overlap, hazards, stalls, and the throughput intuition behind pipelines.",
				sourceRef: "Page 21",
				conceptIds: ["concept-pipelining", "concept-pipeline-hazards"],
			},
		],
	},
	{
		id: "res-cache-video",
		workspaceId: "ws-coa",
		title: "Cache Mapping YouTube Lecture",
		type: "youtube",
		status: "ready",
		url: "https://youtube.com/watch?v=mock-cache-mapping",
		sourceLabel: "YouTube - 34 min",
		summary:
			"A visual lecture comparing direct, associative, and set-associative cache mapping with block-address examples.",
		conceptsFound: 5,
		flashcardsGenerated: 22,
		weakConcepts: 2,
		lastOpenedAt: "2026-05-21T21:08:00.000+05:30",
		addedAt: "2026-05-18T18:12:00.000+05:30",
		readingTimeMinutes: 18,
		progress: 62,
		durationMinutes: 34,
		tags: ["video", "cache", "visual"],
		sections: [
			{
				id: "sec-video-direct",
				title: "Direct mapping walkthrough",
				summary: "Explains block number modulo cache line count and common conflict misses.",
				sourceRef: "08:20",
				conceptIds: ["concept-direct-mapping", "concept-cache-mapping"],
			},
			{
				id: "sec-video-associative",
				title: "Associative lookup",
				summary: "Shows tag matching across all cache lines and why hardware cost rises.",
				sourceRef: "18:45",
				conceptIds: ["concept-associative-mapping", "concept-set-associative-mapping"],
			},
		],
	},
	{
		id: "res-os-notes",
		workspaceId: "ws-coa",
		title: "Operating System Notes",
		type: "notes",
		status: "processing",
		sourceLabel: "Imported notes",
		summary: "Imported notes are being organized into virtual memory, paging, and address translation concepts.",
		conceptsFound: 6,
		flashcardsGenerated: 11,
		weakConcepts: 1,
		lastOpenedAt: null,
		addedAt: "2026-05-22T06:55:00.000+05:30",
		readingTimeMinutes: 24,
		progress: 34,
		tags: ["virtual-memory", "os", "notes"],
		sections: [
			{
				id: "sec-os-paging",
				title: "Paging notes",
				summary: "Early extraction suggests this section should connect to virtual memory repair.",
				sourceRef: "Notebook section 2",
				conceptIds: ["concept-virtual-memory"],
			},
		],
	},
	{
		id: "res-ai-paper",
		workspaceId: "ws-ml",
		title: "AI Research Paper.pdf",
		type: "pdf",
		status: "ready",
		fileName: "AI Research Paper.pdf",
		sourceLabel: "PDF - Research paper",
		summary: "Paper notes on representation learning, evaluation, and failure modes in small benchmark settings.",
		conceptsFound: 8,
		flashcardsGenerated: 19,
		weakConcepts: 3,
		lastOpenedAt: "2026-05-19T19:30:00.000+05:30",
		addedAt: "2026-05-12T13:05:00.000+05:30",
		readingTimeMinutes: 62,
		progress: 39,
		pages: 14,
		tags: ["research", "ml", "paper"],
		sections: [
			{
				id: "sec-ai-eval",
				title: "Evaluation notes",
				summary: "Summarizes why validation leakage can inflate benchmark performance.",
				sourceRef: "Page 8",
				conceptIds: ["concept-overfitting"],
			},
		],
	},
	{
		id: "res-js-closures",
		workspaceId: "ws-fullstack",
		title: "JavaScript Closures Article",
		type: "web",
		status: "ready",
		url: "https://developer.example.com/javascript-closures",
		sourceLabel: "Web article",
		summary: "A practical explanation of closures, lexical scope, and common async interview questions.",
		conceptsFound: 7,
		flashcardsGenerated: 16,
		weakConcepts: 1,
		lastOpenedAt: "2026-05-21T22:10:00.000+05:30",
		addedAt: "2026-05-13T09:25:00.000+05:30",
		readingTimeMinutes: 14,
		progress: 84,
		tags: ["javascript", "closures", "interview"],
		sections: [
			{
				id: "sec-js-lexical",
				title: "Lexical environment",
				summary: "Explains why inner functions retain access to outer variables.",
				sourceRef: "Section 3",
				conceptIds: ["concept-react-state"],
			},
		],
	},
	{
		id: "res-next-notes",
		workspaceId: "ws-fullstack",
		title: "Next.js App Router Notes",
		type: "notes",
		status: "ready",
		sourceLabel: "Manual notes",
		summary: "Personal notes on layouts, loading UI, route groups, server components, and mutation boundaries.",
		conceptsFound: 9,
		flashcardsGenerated: 21,
		weakConcepts: 2,
		lastOpenedAt: "2026-05-20T20:05:00.000+05:30",
		addedAt: "2026-05-09T18:40:00.000+05:30",
		readingTimeMinutes: 22,
		progress: 57,
		tags: ["nextjs", "routing", "react"],
		sections: [
			{
				id: "sec-next-routes",
				title: "Route groups and layouts",
				summary: "Contrasts UI organization with URL structure and persistent layout behavior.",
				sourceRef: "Note block 4",
				conceptIds: ["concept-next-routing"],
			},
		],
	},
];

export const mockConcepts: Concept[] = [
	{
		id: "concept-number-systems",
		workspaceId: "ws-coa",
		title: "Number Systems",
		status: "mastered",
		mastery: 92,
		memoryStrength: 90,
		confidence: 88,
		description: "Binary, octal, decimal, hexadecimal conversion and signed number representation.",
		prerequisiteIds: [],
		relatedConceptIds: ["concept-instruction-cycle"],
		sourceResourceIds: ["res-coa-module-1"],
		lastPracticedAt: "2026-05-21T18:30:00.000+05:30",
		nextReviewAt: "2026-05-28T09:00:00.000+05:30",
		recommendedAction: "Maintain with one quick conversion drill.",
	},
	{
		id: "concept-instruction-cycle",
		workspaceId: "ws-coa",
		title: "Instruction Cycle",
		status: "learning",
		mastery: 73,
		memoryStrength: 76,
		confidence: 70,
		description: "Fetch, decode, execute, memory access, and write-back phases in CPU operation.",
		prerequisiteIds: ["concept-number-systems"],
		relatedConceptIds: ["concept-pipelining"],
		sourceResourceIds: ["res-coa-module-1"],
		lastPracticedAt: "2026-05-22T07:10:00.000+05:30",
		nextReviewAt: "2026-05-23T08:00:00.000+05:30",
		recommendedAction: "Explain the cycle aloud once before pipeline review.",
	},
	{
		id: "concept-addressing-modes",
		workspaceId: "ws-coa",
		title: "Addressing Modes",
		status: "weak",
		mastery: 46,
		memoryStrength: 42,
		confidence: 39,
		description: "The method used by an instruction to locate operands in registers or memory.",
		prerequisiteIds: ["concept-instruction-cycle"],
		relatedConceptIds: ["concept-memory-hierarchy"],
		sourceResourceIds: ["res-coa-module-1"],
		lastPracticedAt: "2026-05-20T17:00:00.000+05:30",
		nextReviewAt: "2026-05-22T15:00:00.000+05:30",
		recommendedAction: "Repair with three worked examples and a 5-card recall loop.",
	},
	{
		id: "concept-memory-hierarchy",
		workspaceId: "ws-coa",
		title: "Memory Hierarchy",
		status: "learning",
		mastery: 69,
		memoryStrength: 72,
		confidence: 67,
		description: "Layering memory by speed, size, cost, and locality of reference.",
		prerequisiteIds: [],
		relatedConceptIds: ["concept-cache-mapping", "concept-virtual-memory"],
		sourceResourceIds: ["res-coa-module-1", "res-cache-video"],
		lastPracticedAt: "2026-05-22T07:25:00.000+05:30",
		nextReviewAt: "2026-05-23T09:30:00.000+05:30",
		recommendedAction: "Review the latency ladder and connect it to cache motivation.",
	},
	{
		id: "concept-cache-mapping",
		workspaceId: "ws-coa",
		title: "Cache Mapping",
		status: "weak",
		mastery: 52,
		memoryStrength: 49,
		confidence: 44,
		description: "How main-memory blocks are mapped into cache locations.",
		prerequisiteIds: ["concept-memory-hierarchy"],
		relatedConceptIds: ["concept-direct-mapping", "concept-associative-mapping", "concept-set-associative-mapping"],
		sourceResourceIds: ["res-coa-module-1", "res-cache-video"],
		lastPracticedAt: "2026-05-21T21:10:00.000+05:30",
		nextReviewAt: "2026-05-22T12:00:00.000+05:30",
		recommendedAction: "Do a 5-minute explanation, then solve two block-address mapping examples.",
	},
	{
		id: "concept-direct-mapping",
		workspaceId: "ws-coa",
		title: "Direct Mapping",
		status: "learning",
		mastery: 61,
		memoryStrength: 58,
		confidence: 55,
		description: "Each memory block maps to exactly one cache line using modulo arithmetic.",
		prerequisiteIds: ["concept-cache-mapping"],
		relatedConceptIds: ["concept-associative-mapping"],
		sourceResourceIds: ["res-cache-video"],
		lastPracticedAt: "2026-05-21T21:20:00.000+05:30",
		nextReviewAt: "2026-05-22T18:00:00.000+05:30",
		recommendedAction: "Practice conflict-miss examples.",
	},
	{
		id: "concept-associative-mapping",
		workspaceId: "ws-coa",
		title: "Associative Mapping",
		status: "weak",
		mastery: 38,
		memoryStrength: 34,
		confidence: 31,
		description: "A block may be placed in any cache line, requiring tag comparison across lines.",
		prerequisiteIds: ["concept-cache-mapping"],
		relatedConceptIds: ["concept-set-associative-mapping"],
		sourceResourceIds: ["res-cache-video", "res-coa-module-1"],
		lastPracticedAt: "2026-05-19T16:00:00.000+05:30",
		nextReviewAt: "2026-05-22T11:30:00.000+05:30",
		recommendedAction: "Ask the tutor for a simple analogy and complete a recall checkpoint.",
	},
	{
		id: "concept-set-associative-mapping",
		workspaceId: "ws-coa",
		title: "Set Associative Mapping",
		status: "learning",
		mastery: 57,
		memoryStrength: 55,
		confidence: 52,
		description: "A compromise where blocks map to a set, then can occupy any line within that set.",
		prerequisiteIds: ["concept-direct-mapping", "concept-associative-mapping"],
		relatedConceptIds: ["concept-cache-mapping"],
		sourceResourceIds: ["res-cache-video"],
		lastPracticedAt: "2026-05-21T21:32:00.000+05:30",
		nextReviewAt: "2026-05-22T17:00:00.000+05:30",
		recommendedAction: "Compare it directly against direct mapping in a two-column note.",
	},
	{
		id: "concept-pipelining",
		workspaceId: "ws-coa",
		title: "Pipelining",
		status: "learning",
		mastery: 66,
		memoryStrength: 64,
		confidence: 60,
		description: "Overlapping instruction execution stages to improve throughput.",
		prerequisiteIds: ["concept-instruction-cycle"],
		relatedConceptIds: ["concept-pipeline-hazards"],
		sourceResourceIds: ["res-coa-module-1"],
		lastPracticedAt: "2026-05-22T07:38:00.000+05:30",
		nextReviewAt: "2026-05-23T07:45:00.000+05:30",
		recommendedAction: "Review the 5-stage pipeline diagram before hazards.",
	},
	{
		id: "concept-pipeline-hazards",
		workspaceId: "ws-coa",
		title: "Pipeline Hazards",
		status: "weak",
		mastery: 35,
		memoryStrength: 30,
		confidence: 29,
		description: "Structural, data, and control conflicts that force stalls or forwarding.",
		prerequisiteIds: ["concept-pipelining"],
		relatedConceptIds: ["concept-instruction-cycle"],
		sourceResourceIds: ["res-coa-module-1"],
		lastPracticedAt: "2026-05-18T20:00:00.000+05:30",
		nextReviewAt: "2026-05-22T10:00:00.000+05:30",
		recommendedAction: "Repair now with a tutor-led example and a 5-question quiz.",
	},
	{
		id: "concept-virtual-memory",
		workspaceId: "ws-coa",
		title: "Virtual Memory",
		status: "weak",
		mastery: 44,
		memoryStrength: 40,
		confidence: 34,
		description: "Address abstraction using pages, frames, page tables, and demand paging.",
		prerequisiteIds: ["concept-memory-hierarchy"],
		relatedConceptIds: ["concept-addressing-modes"],
		sourceResourceIds: ["res-os-notes"],
		lastPracticedAt: null,
		nextReviewAt: "2026-05-22T19:00:00.000+05:30",
		recommendedAction: "Wait for OS notes processing, then generate a source-grounded summary.",
	},
	{
		id: "concept-react-state",
		workspaceId: "ws-fullstack",
		title: "React State",
		status: "learning",
		mastery: 68,
		memoryStrength: 70,
		confidence: 64,
		description: "Local state, derived state, effects, and where state should live.",
		prerequisiteIds: [],
		relatedConceptIds: ["concept-next-routing"],
		sourceResourceIds: ["res-js-closures"],
		lastPracticedAt: "2026-05-21T22:20:00.000+05:30",
		nextReviewAt: "2026-05-24T10:00:00.000+05:30",
		recommendedAction: "Build a tiny state machine example.",
	},
	{
		id: "concept-next-routing",
		workspaceId: "ws-fullstack",
		title: "Next.js Routing",
		status: "learning",
		mastery: 59,
		memoryStrength: 62,
		confidence: 57,
		description: "Route segments, nested layouts, loading UI, and route groups.",
		prerequisiteIds: ["concept-react-state"],
		relatedConceptIds: ["concept-server-actions"],
		sourceResourceIds: ["res-next-notes"],
		lastPracticedAt: "2026-05-20T20:05:00.000+05:30",
		nextReviewAt: "2026-05-23T12:00:00.000+05:30",
		recommendedAction: "Sketch the route tree from memory.",
	},
	{
		id: "concept-server-actions",
		workspaceId: "ws-fullstack",
		title: "Server Actions",
		status: "weak",
		mastery: 41,
		memoryStrength: 37,
		confidence: 35,
		description: "Server-side mutations callable from forms and client transitions.",
		prerequisiteIds: ["concept-next-routing"],
		relatedConceptIds: ["concept-db-indexes"],
		sourceResourceIds: ["res-next-notes"],
		lastPracticedAt: null,
		nextReviewAt: "2026-05-23T18:00:00.000+05:30",
		recommendedAction: "Make two flashcards contrasting actions and route handlers.",
	},
	{
		id: "concept-db-indexes",
		workspaceId: "ws-fullstack",
		title: "Database Indexes",
		status: "weak",
		mastery: 48,
		memoryStrength: 45,
		confidence: 42,
		description: "Data structures that speed reads while adding write and storage tradeoffs.",
		prerequisiteIds: [],
		relatedConceptIds: ["concept-server-actions"],
		sourceResourceIds: [],
		lastPracticedAt: "2026-05-17T19:00:00.000+05:30",
		nextReviewAt: "2026-05-23T14:00:00.000+05:30",
		recommendedAction: "Create one example query and decide which index helps.",
	},
	{
		id: "concept-gradient-descent",
		workspaceId: "ws-ml",
		title: "Gradient Descent",
		status: "weak",
		mastery: 45,
		memoryStrength: 43,
		confidence: 41,
		description: "Iteratively adjusting parameters in the direction that reduces loss.",
		prerequisiteIds: [],
		relatedConceptIds: ["concept-regularization"],
		sourceResourceIds: ["res-ai-paper"],
		lastPracticedAt: "2026-05-19T19:30:00.000+05:30",
		nextReviewAt: "2026-05-23T09:00:00.000+05:30",
		recommendedAction: "Animate the loss curve and explain learning rate tradeoffs.",
	},
	{
		id: "concept-overfitting",
		workspaceId: "ws-ml",
		title: "Overfitting",
		status: "learning",
		mastery: 63,
		memoryStrength: 60,
		confidence: 58,
		description: "When a model memorizes training patterns that do not generalize.",
		prerequisiteIds: [],
		relatedConceptIds: ["concept-regularization"],
		sourceResourceIds: ["res-ai-paper"],
		lastPracticedAt: "2026-05-19T19:45:00.000+05:30",
		nextReviewAt: "2026-05-24T09:00:00.000+05:30",
		recommendedAction: "Contrast validation loss and training loss curves.",
	},
	{
		id: "concept-regularization",
		workspaceId: "ws-ml",
		title: "Regularization",
		status: "weak",
		mastery: 39,
		memoryStrength: 36,
		confidence: 33,
		description: "Techniques that constrain a model to improve generalization.",
		prerequisiteIds: ["concept-overfitting"],
		relatedConceptIds: ["concept-gradient-descent"],
		sourceResourceIds: ["res-ai-paper"],
		lastPracticedAt: null,
		nextReviewAt: "2026-05-23T11:00:00.000+05:30",
		recommendedAction: "Ask for a comparison of L1, L2, and dropout.",
	},
	{
		id: "concept-word-roots",
		workspaceId: "ws-vocab",
		title: "Word Roots",
		status: "learning",
		mastery: 62,
		memoryStrength: 64,
		confidence: 61,
		description: "Greek and Latin roots that help infer unfamiliar word meanings.",
		prerequisiteIds: [],
		relatedConceptIds: ["concept-context-clues"],
		sourceResourceIds: [],
		lastPracticedAt: "2026-05-17T08:15:00.000+05:30",
		nextReviewAt: "2026-05-24T08:00:00.000+05:30",
		recommendedAction: "Practice 10 roots with original example sentences.",
	},
	{
		id: "concept-context-clues",
		workspaceId: "ws-vocab",
		title: "Context Clues",
		status: "mastered",
		mastery: 84,
		memoryStrength: 83,
		confidence: 80,
		description: "Using surrounding words to infer meaning, tone, and usage.",
		prerequisiteIds: [],
		relatedConceptIds: ["concept-word-roots"],
		sourceResourceIds: [],
		lastPracticedAt: "2026-05-16T07:50:00.000+05:30",
		nextReviewAt: "2026-05-27T08:00:00.000+05:30",
		recommendedAction: "Maintain with a short reading passage.",
	},
];

export const mockFlashcards: Flashcard[] = [
	{
		id: "card-direct-mapping-definition",
		workspaceId: "ws-coa",
		conceptId: "concept-direct-mapping",
		resourceId: "res-cache-video",
		type: "basic",
		front: "What is direct cache mapping?",
		back: "A cache organization where each main-memory block maps to exactly one cache line, usually using block number modulo number of cache lines.",
		difficulty: 3,
		intervalDays: 1,
		easeFactor: 2.3,
		repetitions: 2,
		lapses: 1,
		strength: 48,
		dueAt: "2026-05-22T08:00:00.000+05:30",
		lastReviewedAt: "2026-05-21T08:00:00.000+05:30",
		sourceCitation: {
			id: "cite-direct-video",
			resourceId: "res-cache-video",
			label: "Cache Mapping YouTube Lecture",
			location: "08:20",
			url: "https://youtube.com/watch?v=mock-cache-mapping&t=500s",
		},
		tags: ["cache", "mapping", "exam"],
	},
	{
		id: "card-associative-cost",
		workspaceId: "ws-coa",
		conceptId: "concept-associative-mapping",
		resourceId: "res-cache-video",
		type: "application",
		front: "Why is fully associative mapping more expensive in hardware?",
		back: "Because the cache must compare the requested tag against many or all cache lines in parallel, increasing comparator and control complexity.",
		difficulty: 4,
		intervalDays: 0,
		easeFactor: 2.1,
		repetitions: 1,
		lapses: 1,
		strength: 32,
		dueAt: "2026-05-22T07:30:00.000+05:30",
		lastReviewedAt: "2026-05-20T19:15:00.000+05:30",
		sourceCitation: {
			id: "cite-assoc-video",
			resourceId: "res-cache-video",
			label: "Cache Mapping YouTube Lecture",
			location: "18:45",
		},
		tags: ["cache", "hardware-cost"],
	},
	{
		id: "card-pipeline-hazards",
		workspaceId: "ws-coa",
		conceptId: "concept-pipeline-hazards",
		resourceId: "res-coa-module-1",
		type: "basic",
		front: "Name the three main pipeline hazards.",
		back: "Structural hazards, data hazards, and control hazards.",
		difficulty: 2,
		intervalDays: 0,
		easeFactor: 2.4,
		repetitions: 0,
		lapses: 0,
		strength: 28,
		dueAt: "2026-05-22T09:00:00.000+05:30",
		lastReviewedAt: null,
		sourceCitation: {
			id: "cite-pipeline-hazards",
			resourceId: "res-coa-module-1",
			label: "COA Module 1.pdf",
			location: "Page 21",
		},
		tags: ["pipeline", "hazards"],
	},
	{
		id: "card-addressing-indirect",
		workspaceId: "ws-coa",
		conceptId: "concept-addressing-modes",
		resourceId: "res-coa-module-1",
		type: "basic",
		front: "In indirect addressing, what does the address field contain?",
		back: "It contains the address of a memory location that stores the effective address of the operand.",
		difficulty: 3,
		intervalDays: 1,
		easeFactor: 2.2,
		repetitions: 1,
		lapses: 1,
		strength: 41,
		dueAt: "2026-05-22T12:30:00.000+05:30",
		lastReviewedAt: "2026-05-20T17:00:00.000+05:30",
		sourceCitation: {
			id: "cite-addressing-page-9",
			resourceId: "res-coa-module-1",
			label: "COA Module 1.pdf",
			location: "Page 9",
		},
		tags: ["addressing", "modes"],
	},
	{
		id: "card-set-associative",
		workspaceId: "ws-coa",
		conceptId: "concept-set-associative-mapping",
		resourceId: "res-cache-video",
		type: "cloze",
		front: "Set associative mapping first chooses a ____ and then a line within that ____.",
		back: "set; set",
		difficulty: 2,
		intervalDays: 2,
		easeFactor: 2.5,
		repetitions: 3,
		lapses: 0,
		strength: 60,
		dueAt: "2026-05-22T18:00:00.000+05:30",
		lastReviewedAt: "2026-05-19T18:00:00.000+05:30",
		tags: ["cache", "cloze"],
	},
	{
		id: "card-virtual-memory-purpose",
		workspaceId: "ws-coa",
		conceptId: "concept-virtual-memory",
		resourceId: "res-os-notes",
		type: "basic",
		front: "What problem does virtual memory solve for programs?",
		back: "It gives each program the illusion of a large, continuous address space while the OS maps virtual pages to physical frames as needed.",
		difficulty: 4,
		intervalDays: 0,
		easeFactor: 2,
		repetitions: 0,
		lapses: 0,
		strength: 29,
		dueAt: "2026-05-22T19:00:00.000+05:30",
		lastReviewedAt: null,
		tags: ["virtual-memory", "os"],
	},
	{
		id: "card-js-closure",
		workspaceId: "ws-fullstack",
		conceptId: "concept-react-state",
		resourceId: "res-js-closures",
		type: "basic",
		front: "What is a JavaScript closure?",
		back: "A function bundled with references to variables from its lexical environment, even after the outer function has returned.",
		difficulty: 2,
		intervalDays: 3,
		easeFactor: 2.6,
		repetitions: 4,
		lapses: 0,
		strength: 76,
		dueAt: "2026-05-23T09:30:00.000+05:30",
		lastReviewedAt: "2026-05-20T22:10:00.000+05:30",
		tags: ["javascript", "closures"],
	},
	{
		id: "card-server-actions",
		workspaceId: "ws-fullstack",
		conceptId: "concept-server-actions",
		resourceId: "res-next-notes",
		type: "application",
		front: "When would you use a Server Action instead of a client-side fetch call?",
		back: "When a mutation can run on the server from a form or transition, keeping secrets server-side and reducing manual API route plumbing.",
		difficulty: 4,
		intervalDays: 0,
		easeFactor: 2.1,
		repetitions: 1,
		lapses: 1,
		strength: 35,
		dueAt: "2026-05-22T22:00:00.000+05:30",
		lastReviewedAt: "2026-05-21T20:00:00.000+05:30",
		tags: ["nextjs", "server-actions"],
	},
	{
		id: "card-gradient-descent",
		workspaceId: "ws-ml",
		conceptId: "concept-gradient-descent",
		resourceId: "res-ai-paper",
		type: "basic",
		front: "What does gradient descent update on each step?",
		back: "Model parameters, moving them in the direction that reduces the loss according to the gradient.",
		difficulty: 3,
		intervalDays: 1,
		easeFactor: 2.2,
		repetitions: 1,
		lapses: 0,
		strength: 44,
		dueAt: "2026-05-23T09:00:00.000+05:30",
		lastReviewedAt: "2026-05-19T19:30:00.000+05:30",
		tags: ["ml", "optimization"],
	},
	{
		id: "card-regularization",
		workspaceId: "ws-ml",
		conceptId: "concept-regularization",
		resourceId: "res-ai-paper",
		type: "basic",
		front: "Why does regularization help with overfitting?",
		back: "It discourages overly complex models, making learned patterns more likely to generalize beyond the training set.",
		difficulty: 4,
		intervalDays: 0,
		easeFactor: 2,
		repetitions: 0,
		lapses: 0,
		strength: 33,
		dueAt: "2026-05-23T11:00:00.000+05:30",
		lastReviewedAt: null,
		tags: ["ml", "generalization"],
	},
	{
		id: "card-word-root-bene",
		workspaceId: "ws-vocab",
		conceptId: "concept-word-roots",
		type: "basic",
		front: "What does the root 'bene' usually mean?",
		back: "Good or well, as in benefit, benevolent, and benefactor.",
		difficulty: 1,
		intervalDays: 5,
		easeFactor: 2.7,
		repetitions: 5,
		lapses: 0,
		strength: 81,
		dueAt: "2026-05-24T08:00:00.000+05:30",
		lastReviewedAt: "2026-05-17T08:15:00.000+05:30",
		tags: ["vocabulary", "roots"],
	},
	{
		id: "card-context-clues",
		workspaceId: "ws-vocab",
		conceptId: "concept-context-clues",
		type: "application",
		front: "If a sentence contrasts a word with 'careless', what kind of clue is it giving?",
		back: "A contrast clue, helping infer that the unknown word may mean careful or deliberate.",
		difficulty: 2,
		intervalDays: 7,
		easeFactor: 2.8,
		repetitions: 6,
		lapses: 0,
		strength: 86,
		dueAt: "2026-05-27T08:00:00.000+05:30",
		lastReviewedAt: "2026-05-16T07:50:00.000+05:30",
		tags: ["vocabulary", "reading"],
	},
];

export const mockRecallAttempts: RecallAttempt[] = [
	{
		id: "attempt-1",
		flashcardId: "card-direct-mapping-definition",
		workspaceId: "ws-coa",
		rating: "good",
		answeredAt: "2026-05-21T08:00:00.000+05:30",
		responseTimeSeconds: 18,
		previousStrength: 38,
		nextStrength: 48,
	},
	{
		id: "attempt-2",
		flashcardId: "card-associative-cost",
		workspaceId: "ws-coa",
		rating: "hard",
		answeredAt: "2026-05-20T19:15:00.000+05:30",
		responseTimeSeconds: 42,
		previousStrength: 35,
		nextStrength: 32,
	},
	{
		id: "attempt-3",
		flashcardId: "card-js-closure",
		workspaceId: "ws-fullstack",
		rating: "easy",
		answeredAt: "2026-05-20T22:10:00.000+05:30",
		responseTimeSeconds: 11,
		previousStrength: 65,
		nextStrength: 76,
	},
];

export const mockLearningPlans: LearningPlan[] = [
	{
		id: "plan-coa-end-sem",
		workspaceId: "ws-coa",
		title: "COA End Sem Sprint",
		goal: "Reach 75% readiness before the COA end-sem exam.",
		deadline: "2026-05-24T18:00:00.000+05:30",
		availableMinutesPerDay: 360,
		currentReadiness: 61,
		status: "active",
		generatedAt: "2026-05-22T07:00:00.000+05:30",
		view: "path",
		days: [
			{
				id: "plan-coa-day-1",
				dayNumber: 1,
				date: "2026-05-22",
				theme: "Memory hierarchy and cache mapping",
				totalMinutes: 90,
				tasks: [
					{
						id: "task-learn-cache",
						kind: "learn",
						title: "Learn: Cache Mapping",
						description: "Review direct, associative, and set-associative mapping from the video and module PDF.",
						minutes: 25,
						status: "not-started",
						priority: "high",
						conceptIds: ["concept-cache-mapping", "concept-direct-mapping", "concept-associative-mapping"],
						resourceIds: ["res-cache-video", "res-coa-module-1"],
					},
					{
						id: "task-recall-cache",
						kind: "recall",
						title: "Recall: 18 cards due",
						description: "Clear due cards for cache mapping and addressing modes.",
						minutes: 15,
						status: "not-started",
						priority: "high",
						conceptIds: ["concept-cache-mapping", "concept-addressing-modes"],
						resourceIds: ["res-coa-module-1", "res-cache-video"],
					},
					{
						id: "task-practice-pyq",
						kind: "practice",
						title: "Practice: 5 PYQs",
						description: "Solve previous-year questions on memory hierarchy and cache mapping.",
						minutes: 20,
						status: "not-started",
						priority: "medium",
						conceptIds: ["concept-memory-hierarchy", "concept-cache-mapping"],
						resourceIds: ["res-coa-module-1"],
					},
					{
						id: "task-repair-pipeline",
						kind: "repair",
						title: "Repair: Pipeline Hazards",
						description: "Use tutor mode to repair structural, data, and control hazards.",
						minutes: 10,
						status: "not-started",
						priority: "high",
						conceptIds: ["concept-pipeline-hazards"],
						resourceIds: ["res-coa-module-1"],
					},
				],
			},
			{
				id: "plan-coa-day-2",
				dayNumber: 2,
				date: "2026-05-23",
				theme: "Pipelining, hazards, and weak-point repair",
				totalMinutes: 110,
				tasks: [
					{
						id: "task-pipeline-diagram",
						kind: "learn",
						title: "Draw the 5-stage pipeline from memory",
						description: "Rebuild the pipeline diagram and annotate where hazards appear.",
						minutes: 25,
						status: "not-started",
						priority: "high",
						conceptIds: ["concept-pipelining", "concept-pipeline-hazards"],
						resourceIds: ["res-coa-module-1"],
					},
					{
						id: "task-hazard-quiz",
						kind: "quiz",
						title: "Hazards quiz",
						description: "Answer 10 source-grounded questions on stalls, forwarding, and branching.",
						minutes: 20,
						status: "not-started",
						priority: "high",
						conceptIds: ["concept-pipeline-hazards"],
						resourceIds: ["res-coa-module-1"],
					},
					{
						id: "task-formula-recall",
						kind: "recall",
						title: "Formula recall",
						description: "Review cache address split and average memory access time formulas.",
						minutes: 20,
						status: "not-started",
						priority: "medium",
						conceptIds: ["concept-cache-mapping", "concept-memory-hierarchy"],
						resourceIds: ["res-coa-module-1", "res-cache-video"],
					},
					{
						id: "task-final-mock",
						kind: "practice",
						title: "Mini mock",
						description: "Complete one timed mixed-section mock and repair missed concepts.",
						minutes: 45,
						status: "not-started",
						priority: "high",
						conceptIds: ["concept-addressing-modes", "concept-cache-mapping", "concept-pipeline-hazards"],
						resourceIds: ["res-coa-module-1", "res-cache-video"],
					},
				],
			},
			{
				id: "plan-coa-day-3",
				dayNumber: 3,
				date: "2026-05-24",
				theme: "Final consolidation",
				totalMinutes: 75,
				tasks: [
					{
						id: "task-final-recall",
						kind: "recall",
						title: "Morning spaced repetition",
						description: "Only due and weak cards; do not add new material unless a gap appears.",
						minutes: 20,
						status: "not-started",
						priority: "high",
						conceptIds: ["concept-cache-mapping", "concept-pipeline-hazards", "concept-addressing-modes"],
						resourceIds: ["res-coa-module-1", "res-cache-video"],
					},
					{
						id: "task-final-repair",
						kind: "repair",
						title: "Repair weakest three concepts",
						description: "Ask the tutor for one simple explanation and one exam-style question per weak concept.",
						minutes: 30,
						status: "not-started",
						priority: "high",
						conceptIds: ["concept-pipeline-hazards", "concept-cache-mapping", "concept-addressing-modes"],
						resourceIds: ["res-coa-module-1", "res-cache-video"],
					},
					{
						id: "task-final-summary",
						kind: "review",
						title: "One-page final sheet",
						description: "Write one page from memory: cache mapping, hazards, addressing modes, and virtual memory.",
						minutes: 25,
						status: "not-started",
						priority: "medium",
						conceptIds: ["concept-cache-mapping", "concept-pipeline-hazards", "concept-addressing-modes", "concept-virtual-memory"],
						resourceIds: ["res-coa-module-1", "res-os-notes"],
					},
				],
			},
		],
	},
	{
		id: "plan-fullstack-mvp",
		workspaceId: "ws-fullstack",
		title: "Full Stack MVP Build Path",
		goal: "Turn core Next.js and data concepts into a small production-style app.",
		deadline: "2026-06-12T20:00:00.000+05:30",
		availableMinutesPerDay: 90,
		currentReadiness: 58,
		status: "active",
		generatedAt: "2026-05-20T19:00:00.000+05:30",
		view: "path",
		days: [
			{
				id: "plan-fullstack-day-1",
				dayNumber: 1,
				date: "2026-05-23",
				theme: "Routing and state foundations",
				totalMinutes: 70,
				tasks: [
					{
						id: "task-next-routing",
						kind: "learn",
						title: "Build route map from memory",
						description: "Explain nested layouts, route groups, and loading UI without notes.",
						minutes: 25,
						status: "not-started",
						priority: "medium",
						conceptIds: ["concept-next-routing"],
						resourceIds: ["res-next-notes"],
					},
					{
						id: "task-server-actions",
						kind: "repair",
						title: "Repair Server Actions",
						description: "Generate two examples that contrast Server Actions and route handlers.",
						minutes: 25,
						status: "not-started",
						priority: "high",
						conceptIds: ["concept-server-actions"],
						resourceIds: ["res-next-notes"],
					},
					{
						id: "task-fullstack-recall",
						kind: "recall",
						title: "Review 9 due cards",
						description: "Focus on closure and server mutation flashcards.",
						minutes: 20,
						status: "not-started",
						priority: "medium",
						conceptIds: ["concept-react-state", "concept-server-actions"],
						resourceIds: ["res-js-closures", "res-next-notes"],
					},
				],
			},
		],
	},
];

export const mockTutorMessages: TutorMessage[] = [
	{
		id: "msg-user-cache",
		role: "user",
		content: "Explain cache mapping simply.",
		workspaceId: "ws-coa",
		resourceId: "res-cache-video",
		mode: "explain",
		createdAt: "2026-05-22T07:50:00.000+05:30",
	},
	{
		id: "msg-ai-cache",
		role: "assistant",
		content:
			"Think of cache as a small fast notebook beside the CPU. Cache mapping is the rule for deciding where a page from the big textbook is allowed to go in that notebook. Direct mapping gives each page one fixed slot, associative mapping lets it use any slot, and set associative mapping gives it a small section of possible slots.",
		workspaceId: "ws-coa",
		resourceId: "res-cache-video",
		mode: "explain",
		createdAt: "2026-05-22T07:50:12.000+05:30",
		citations: [
			{
				id: "cite-ai-cache-1",
				resourceId: "res-cache-video",
				label: "Cache Mapping YouTube Lecture",
				location: "08:20",
			},
			{
				id: "cite-ai-cache-2",
				resourceId: "res-coa-module-1",
				label: "COA Module 1.pdf",
				location: "Page 4",
			},
		],
		quickActions: [
			{ id: "qa-flashcards", label: "Turn into flashcards", action: "flashcards" },
			{ id: "qa-quiz", label: "Quiz me on this", action: "quiz" },
			{ id: "qa-simpler", label: "Explain simpler", action: "simpler" },
		],
	},
];

export const mockProgressSnapshots: ProgressSnapshot[] = [
	{
		id: "progress-2026-05-15",
		date: "2026-05-15",
		workspaceId: "ws-coa",
		examReadiness: 34,
		memoryStrength: 52,
		conceptCoverage: 31,
		recallAccuracy: 68,
		minutesStudied: 28,
		cardsReviewed: 12,
	},
	{
		id: "progress-2026-05-16",
		date: "2026-05-16",
		workspaceId: "ws-coa",
		examReadiness: 39,
		memoryStrength: 57,
		conceptCoverage: 38,
		recallAccuracy: 72,
		minutesStudied: 42,
		cardsReviewed: 18,
	},
	{
		id: "progress-2026-05-17",
		date: "2026-05-17",
		workspaceId: "ws-coa",
		examReadiness: 43,
		memoryStrength: 61,
		conceptCoverage: 43,
		recallAccuracy: 74,
		minutesStudied: 35,
		cardsReviewed: 16,
	},
	{
		id: "progress-2026-05-18",
		date: "2026-05-18",
		workspaceId: "ws-coa",
		examReadiness: 48,
		memoryStrength: 64,
		conceptCoverage: 50,
		recallAccuracy: 77,
		minutesStudied: 54,
		cardsReviewed: 22,
	},
	{
		id: "progress-2026-05-19",
		date: "2026-05-19",
		workspaceId: "ws-coa",
		examReadiness: 51,
		memoryStrength: 68,
		conceptCoverage: 55,
		recallAccuracy: 79,
		minutesStudied: 63,
		cardsReviewed: 24,
	},
	{
		id: "progress-2026-05-20",
		date: "2026-05-20",
		workspaceId: "ws-coa",
		examReadiness: 55,
		memoryStrength: 71,
		conceptCoverage: 59,
		recallAccuracy: 81,
		minutesStudied: 47,
		cardsReviewed: 21,
	},
	{
		id: "progress-2026-05-21",
		date: "2026-05-21",
		workspaceId: "ws-coa",
		examReadiness: 59,
		memoryStrength: 75,
		conceptCoverage: 62,
		recallAccuracy: 83,
		minutesStudied: 76,
		cardsReviewed: 31,
	},
	{
		id: "progress-2026-05-22",
		date: "2026-05-22",
		workspaceId: "ws-coa",
		examReadiness: 61,
		memoryStrength: 78,
		conceptCoverage: 64,
		recallAccuracy: 84,
		minutesStudied: 52,
		cardsReviewed: 18,
	},
];

export const mockStudySessions: StudySession[] = [
	{
		id: "session-coa-cache",
		workspaceId: "ws-coa",
		mode: "lesson",
		startedAt: "2026-05-22T07:05:00.000+05:30",
		endedAt: "2026-05-22T07:42:00.000+05:30",
		durationMinutes: 37,
		focusScore: 88,
		completedTaskIds: ["task-learn-cache"],
		notes: "Direct mapping is clear; associative mapping still needs a concrete analogy.",
	},
	{
		id: "session-fullstack-routing",
		workspaceId: "ws-fullstack",
		mode: "recall",
		startedAt: "2026-05-21T21:52:00.000+05:30",
		endedAt: "2026-05-21T22:10:00.000+05:30",
		durationMinutes: 18,
		focusScore: 81,
		completedTaskIds: [],
		notes: "Closure cards felt easy; server mutations need examples.",
	},
	{
		id: "session-ml-paper",
		workspaceId: "ws-ml",
		mode: "lesson",
		startedAt: "2026-05-19T19:05:00.000+05:30",
		endedAt: "2026-05-19T19:50:00.000+05:30",
		durationMinutes: 45,
		focusScore: 74,
		completedTaskIds: [],
		notes: "Regularization needs a better mental model.",
	},
];

export const mockDailyMission: DailyMission = {
	id: "mission-2026-05-22",
	date: "2026-05-22",
	totalMinutes: 52,
	items: [
		{
			id: "mission-learn-cache",
			kind: "learn",
			title: "Learn: Cache Mapping",
			minutes: 25,
			status: "not-started",
			conceptId: "concept-cache-mapping",
			workspaceId: "ws-coa",
		},
		{
			id: "mission-recall-due",
			kind: "recall",
			title: "Recall: 18 cards due",
			minutes: 15,
			status: "not-started",
			workspaceId: "ws-coa",
		},
		{
			id: "mission-practice-pyq",
			kind: "practice",
			title: "Practice: 5 PYQs",
			minutes: 20,
			status: "not-started",
			conceptId: "concept-memory-hierarchy",
			workspaceId: "ws-coa",
		},
		{
			id: "mission-repair-pipeline",
			kind: "repair",
			title: "Repair: Pipeline Hazards",
			minutes: 10,
			status: "not-started",
			conceptId: "concept-pipeline-hazards",
			workspaceId: "ws-coa",
		},
	],
	coachPrompt:
		"Your weakest concept today is associative mapping. Want a 5-minute explanation or a quiz?",
};

export const mockAISettings: AISettings = {
	provider: "openai",
	apiKey: "",
	model: "gpt-4.1-mini",
	embeddingModel: "text-embedding-3-small",
	useOwnApiKey: false,
	saveChatHistory: true,
	sourceOnlyAnswers: true,
	socraticByDefault: false,
	autoGenerateFlashcards: true,
	autoGenerateQuizzes: true,
};

export const mockBillingUsage: BillingUsage = {
	workspacesUsed: 4,
	resourcesUploaded: 14,
	aiMessages: 218,
	flashcardsGenerated: 127,
	workspaceLimit: "unlimited",
	resourceLimit: "unlimited",
	aiMessageLimit: "unlimited",
	flashcardLimit: "unlimited",
};
